import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { z } from "zod";

// 1. Initialize the Server
const server = new McpServer({
  name: "spec-kit-mern-helper",
  version: "1.0.0",
});

// 2. Define a Tool: This tool will "Review" the AI's architectural plan
server.tool(
  "analyze_mern_plan",
  "Analyzes a MERN stack plan for best practices",
  {
    plan_text: z.string().describe("The architectural plan generated by the AI")
  },
  async ({ plan_text }) => {
    const findings = [];
    
    // Simple logic: Check if common MERN best practices are mentioned
    if (!plan_text.toLowerCase().includes("zod")) {
      findings.push("⚠️ Suggestion: Add Zod for schema validation.");
    }
    if (!plan_text.toLowerCase().includes("controller")) {
      findings.push("⚠️ Warning: Ensure business logic is separated into controllers.");
    }

    return {
      content: [{ type: "text", text: findings.join("\n") || "✅ Plan looks solid for MERN!" }]
    };
  }
);

// 3. Start the Server using stdio transport
const transport = new StdioServerTransport();
await server.connect(transport);